version: 2.1

jobs:
  build:
    environment:
      NODE_ENV: 'test'
    docker:
      - image: circleci/node:12.10
      - image: mongo:4.2.0
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: 
          name: Install project dependencies
          command: npm install --verbose
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json"}}
          paths:
            - node_modules
      - run:
          name: Run tests
          command: npm test
workflows:
  run_build:
    jobs:
      - build